# .github/workflows/android_release.yml

# This workflow is responsible for building and releasing
# an unsigned Android application APK on GitHub.

name: Android Unsigned Release Build

# Controls when the workflow will run.
on:
  # This workflow is triggered on a push to a tag that matches the 'v*.*.*' pattern.
  # This is a common practice for creating releases (e.g., v1.0.0, v1.2.3-beta).
  push:
    tags:
      - 'v*.*.*' # Matches tags like v1.0.0, v1.0.1, v2.3.4, etc.

# A workflow run is made up of one or more jobs.
jobs:
  build_and_release:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Checkout the repository code.
      # This action checks out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK).
      # Android projects require Java to build. JDK 17 is commonly used for modern Android projects.
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # A popular OpenJDK distribution
          java-version: '17'      # Specify the JDK version required for your Android project

      # Step 3: Make the Gradle wrapper executable.
      # The gradlew script needs executable permissions to run on Linux runners.
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build the Android application in release mode.
      # This action uses Gradle to build the unsigned APK.
      # 'assembleRelease' builds the APK.
      # The 'gradle/gradle-build-action@v2' handles caching and proper Gradle setup.
      - name: Build unsigned Release APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      # Step 5: Create a GitHub Release and upload the unsigned APK.
      # This action creates a new release on GitHub and attaches the unsigned APK
      # file as an asset to that release.
      - name: Create GitHub Release
        # This step only runs if the workflow was triggered by a tag push.
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          # Path to the unsigned release APK file.
          # Adjust this path if your project structure or APK name is different.
          files: app/build/outputs/apk/release/app-release-unsigned.apk
          tag_name: ${{ github.ref_name }} # Uses the pushed tag name as the release tag
          name: Release ${{ github.ref_name }} # Uses the pushed tag name as the release title
          body: | # Markdown content for the release description
            🎉 New Unsigned Release: ${{ github.ref_name }} 🎉

            ### What's New:
            (Add your release notes here. You can also automate this by parsing
            a CHANGELOG.md file or commit messages in a prior step.)

            ### Downloads:
            - app-release-unsigned.apk
          draft: false      # Set to 'true' to create a draft release (not published immediately)
          prerelease: false # Set to 'true' for pre-release versions (e.g., betas)
        env:
          # GITHUB_TOKEN is a special token automatically provided by GitHub Actions
          # with permissions to create releases and upload assets.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional Step: Upload Unsigned APK as a separate workflow artifact (for debugging or archival purposes).
      # This creates a separate artifact bundle in the workflow run, not attached to the GitHub Release.
      - name: Upload Unsigned APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk
