# .github/workflows/android_release.yml

name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Updated to v4 for better security and features
      - uses: actions/checkout@v4
      # Updated to v4 and Java 17 for modern Android builds
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Recommended distribution for setup-java
          java-version: '17'
      # Updated to v2 for the Flutter action
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter pub get
      # Changed from 'flutter format' to 'dart format' to resolve "command not found" error
      # Added 'continue-on-error: true' to allow workflow to proceed even if files were formatted
      - run: dart format --set-exit-if-changed .
        continue-on-error: true # Allow this step to fail if files are changed, but continue the workflow
      - run: flutter analyze .
      - run: flutter build apk
      # Updated to v4 to resolve the deprecation error
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
