# .github/workflows/windows_desktop_build.yml

name: Flutter Windows Desktop Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_windows:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Windows Release App
        run: flutter build windows --release

      - name: Zip Windows Build for Release
        shell: powershell
        run: |
          $sourcePath = "build/windows/x64/runner/Release"
          $zipFileName = "windows-app-v${{ github.run_number }}.zip"
          $destinationDir = "build/windows/runner"
          $zipFilePath = "$destinationDir/$zipFileName"

          if (-not (Test-Path -Path $destinationDir -PathType Container)) {
              New-Item -Path $destinationDir -ItemType Directory -Force
          }

          Compress-Archive -Path "$sourcePath\*" -DestinationPath $zipFilePath

      # NEW STEP: Create GitHub Release and Upload Asset
      - name: Create Release and Upload Windows Asset
        uses: softprops/action-gh-release@v1 # Use action-gh-release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' # Only create on tag pushes or manual trigger
        with:
          tag_name: v${{ github.run_number }} # This will create the tag if it doesn't exist
          name: Release v${{ github.run_number }}
          body: |
            Automated Windows Desktop build for run number ${{ github.run_number }}.
            This release contains the compiled Windows application.
            For more details, see the workflow run.
          files: build/windows/runner/windows-app-v${{ github.run_number }}.zip # Specify the file to upload
          draft: false # Set to true if you want to manually publish later
          prerelease: false # Set to true if this is a pre-release
